// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/components/Breadcrumb/index.vue')['default']
    Collapse: typeof import('./src/components/Collapse/index.vue')['default']
    CurrencyInput: typeof import('./src/components/CurrencyInput/index.vue')['default']
    CurrencySelect: typeof import('./src/components/CurrencySelect/index.vue')['default']
    Detail: typeof import('./src/components/Detail/index.vue')['default']
    DetailItem: typeof import('./src/components/DetailItem/index.vue')['default']
    EditFormItem: typeof import('./src/components/EditFormItem/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Hamburger: typeof import('./src/components/Hamburger/index.vue')['default']
    IconSelect: typeof import('./src/components/IconSelect/index.vue')['default']
    ListPage: typeof import('./src/components/ListPage/index.vue')['default']
    NumberInput: typeof import('./src/components/NumberInput/index.vue')['default']
    NumSpan: typeof import('./src/components/business-components/NumSpan.vue')['default']
    OperationPop: typeof import('./src/components/OperationPop/index.vue')['default']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    PdfPreview: typeof import('./src/components/PdfPreview/index.vue')['default']
    PointEdit: typeof import('./src/components/business-components/user/PointEdit.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screenfull: typeof import('./src/components/Screenfull/index.vue')['default']
    SizeSelect: typeof import('./src/components/SizeSelect/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    ThemePicker: typeof import('./src/components/ThemePicker/index.vue')['default']
    UploadFile: typeof import('./src/components/UploadFile/index.vue')['default']
    UserEdit: typeof import('./src/components/business-components/user/UserEdit.vue')['default']
    VerificationCode: typeof import('./src/components/VerificationCode/index.vue')['default']
    WangEditor: typeof import('./src/components/WangEditor/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
